version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-backend-container
    # 使用nginx代理后端，所以不需要监听端口
    # ports:
    #   - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-frontend-container
    # 用nginx代理前端，所以不需要监听端口
    # ports:
    #   - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    # 使用官方Nginx镜像
    image: nginx:alpine
    container_name: my-nginx-container
    # 将本地的nginx.conf挂载到容器里
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"      # 外部访问80端口(HTTP)
      # 如果要HTTPS，可以自己配置443
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
